---
# - name: Enforce minimum Ansible version
  # ansible.builtin.assert:
    # that: ansible_version.full_version >= '2.7'
    # fail_msg: "This playbook requires Ansible 2.7 or later"

- name: 'Update APT package cache'
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe
  
- name: Install packages
  ansible.builtin.apt:
    pkg:
      - git
      - apt-transport-https
      - ca-certificates
      - wget
      - software-properties-common
      - gnupg2
      - curl
      - xz-utils
      - age
    state: present
    update_cache: true

# Fastfetch is not available in apt
- name: Install Fastfetch
  block:
    - name: Check if Fastfetch is installed
      ansible.builtin.command: |
        dpkg-query -W fastfetch
      register: fastfetch_check
      failed_when: fastfetch_check.rc > 1
      changed_when: false

    - name: Install Fastfetch if not already
      ansible.builtin.apt:
        deb: https://github.com/fastfetch-cli/fastfetch/releases/download/{{ fastfetch_version }}/fastfetch-linux-amd64.deb
        state: present
      when: fastfetch_check.rc == 1

- name: Remove undesirable packages
  ansible.builtin.apt:
    pkg: "{{ unnecessary_software }}"
    state: absent

- name: Stop and disable unnecessary services
  block:
    - name: Check if unnecessary services exist
      ansible.builtin.service_facts:
  
    - name: Disable services
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items: "{{ unnecessary_services }}"
      when: item in ansible_facts.services

- name: Set Fastfetch as motd
  ansible.builtin.template:
    dest: /etc/update-motd.d/90-fastfetch-motd
    src: 90-fastfetch-motd.j2
    owner: root
    group: root
    mode: 0755