---

- name: Add hardened SSH config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: Reload SSH

- name: Debug admin_networks variable
  debug:
    var: admin_networks

- name: Allow SSH from admin networks
  community.general.ufw:
    rule: allow
    port: ssh
    src: "{{ item }}"
  loop: "{{ admin_networks }}"