apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

helmCharts:
- name: traefik
  repo: https://traefik.github.io/charts
  releaseName: traefik
  namespace: traefik
  version: v30.1.0
  valuesFile: values.yaml

resources:
- base/traefik-rbac.yaml
- base/traefik-ingress-route.yaml
- base/traefik-https-redirect-middleware.yaml