apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- base/ingress-route.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml

patchesStrategicMerge:
- patches/argocd-cm.yaml
- patches/argocd-cmd-params-cm.yaml