apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 6.7.1
  namespace: argocd
  apiVersions:
  - v1
  - apiregistration.k8s.io/v1
  - apps/v1
  - events.k8s.io/v1
  - authentication.k8s.io/v1
  - authorization.k8s.io/v1
  - autoscaling/v2
  - autoscaling/v1
  - batch/v1
  - certificates.k8s.io/v1
  - networking.k8s.io/v1
  - policy/v1
  - rbac.authorization.k8s.io/v1
  - storage.k8s.io/v1
  - admissionregistration.k8s.io/v1
  - apiextensions.k8s.io/v1
  - scheduling.k8s.io/v1
  - coordination.k8s.io/v1
  - node.k8s.io/v1
  - discovery.k8s.io/v1
  - flowcontrol.apiserver.k8s.io/v1
  - flowcontrol.apiserver.k8s.io/v1beta3
  - argoproj.io/v1alpha1
  releaseName: argocd
  valuesFile: values.yaml
patches:
- path: argocd-cmd-params-cm-patch.yaml
- patch: "- op: add\n  path: /spec/template/spec/containers/0/env/-\n  value: { name:
    ARGOCD_SYNC_WAVE_DELAY, value: '30' }"
  target:
    version: v1
    group: apps
    kind: StatefulSet
    name: argocd-application-controller
    labelSelector: app.kubernetes.io/name=argocd-application-controller