apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.0/manifests/ha/install.yaml
- resources/argocd-server.yaml
- resources/argocd-repo-server.yaml
- resources/argocd-ingress-route.yaml

patches:
- path: patches/argocd-cm.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
- path: patches/argocd-cmd-params-cm.yaml
  target:
    kind: ConfigMap
    name: argocd-cmd-params-cm