- name: Ansible playbook for all our hosts
  hosts: all
  roles:
    - common
  remote_user: xephrox
  become: yes

- name: K3s cluster prep
  hosts: k3s_cluster
  gather_facts: true
  roles:
    - prereq
  remote_user: xephrox
  become: yes

- name: Setup K3s Master
  hosts: k3s_master
  gather_facts: true
  roles:
    - k3s_master
  remote_user: xephrox
  become: yes

- name: Setup K3s Workers
  hosts: k3s_worker
  gather_facts: true
  roles:
    - k3s_worker
  remote_user: xephrox
  become: yes

- name: Bootstrap Cluster
  hosts: localhost
  gather_facts: true
  roles:
    - bootstrap_cluster
  remote_user: xephrox