apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
  annotations:
    purelb.io/service-group: internal-ipv4
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.dev.xephrox.xyz`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService