# argo-cd-repo-server-ksops-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      # 1. Define an emptyDir volume which will hold the custom binaries
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: sops-age
          secret:
            secretName: sops-age
            items:
              - key: secret.key
                path: keys.txt
      # 2. Use an init container to download/copy custom binaries into the emptyDir
      initContainers:
        - name: install-ksops
          image: viaductoss/ksops:v4.3.2
          command: ["/bin/sh", "-c"]
          args:
            - echo "Installing KSOPS...";
              mkdir -p /custom-tools/home/argocd/.config/kustomize/plugin/viaduct.ai/v1/ksops/;
              mv ksops /custom-tools/home/argocd/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so;
              mv kustomize /custom-tools/;
              echo "Done.";
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      # 3. Volume mount the custom binary to the bin directory (overriding the existing version)
      containers:
        - name: argocd-repo-server
          env:
            - name: KUSTOMIZE_PLUGIN_HOME
              value: /home/argocd/.config/kustomize/plugin
            - name: SOPS_AGE_KEY_FILE
              value: /etc/sops/age/keys.txt
          volumeMounts:
            - mountPath: /etc/sops/age
              name: sops-age
              readOnly: true
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize
            - mountPath: /home/argocd/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so
              name: custom-tools
              subPath: home/argocd/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so